// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlrKXlJixhdU6sULXEqQh7K5h5FyLWOw',
    appId: '1:668329999071:web:5ce3e54cd4f7bc57e1c76a',
    messagingSenderId: '668329999071',
    projectId: 'swigo-a2cc5',
    authDomain: 'swigo-a2cc5.firebaseapp.com',
    storageBucket: 'swigo-a2cc5.firebasestorage.app',
    measurementId: 'G-PKTV3H5BXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7h3bNFTLfHI6TlOjsjv2xvBZLKHpWHA',
    appId: '1:668329999071:android:0a0c1b6ba8cbb831e1c76a',
    messagingSenderId: '668329999071',
    projectId: 'swigo-a2cc5',
    storageBucket: 'swigo-a2cc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY73PSfVERjuyLnLHv-HYcGW0oOQ6HckU',
    appId: '1:668329999071:ios:37620971934d6b0fe1c76a',
    messagingSenderId: '668329999071',
    projectId: 'swigo-a2cc5',
    storageBucket: 'swigo-a2cc5.firebasestorage.app',
    iosBundleId: 'com.example.swigoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY73PSfVERjuyLnLHv-HYcGW0oOQ6HckU',
    appId: '1:668329999071:ios:37620971934d6b0fe1c76a',
    messagingSenderId: '668329999071',
    projectId: 'swigo-a2cc5',
    storageBucket: 'swigo-a2cc5.firebasestorage.app',
    iosBundleId: 'com.example.swigoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIlrKXlJixhdU6sULXEqQh7K5h5FyLWOw',
    appId: '1:668329999071:web:d899e53f541f5280e1c76a',
    messagingSenderId: '668329999071',
    projectId: 'swigo-a2cc5',
    authDomain: 'swigo-a2cc5.firebaseapp.com',
    storageBucket: 'swigo-a2cc5.firebasestorage.app',
    measurementId: 'G-VBVSPPFTY9',
  );
}
